module Interior
  module Meridians
    MERIDIANS = {
      'AL' => [ { :id => 16, :name => 'Huntsville' },
                { :id => 25, :name => 'St. Stephens' },
                { :id => 29, :name => 'Tallahasee' } ],
      'AR' => [ { :id => 5,  :name => '5th' } ],
      'AZ' => [ { :id => 14, :name => 'Gila-Salt River' },
                { :id => 22, :name => 'Navajo' },
                { :id => 27, :name => 'San Bernardino' } ],
      'CA' => [ { :id => 14, :name => 'Gila-Salt River' },
                { :id => 15, :name => 'Humboldt' },
                { :id => 21, :name => 'Mount Diablo' },
                { :id => 27, :name => 'San Bernardino' } ],
      'CO' => [ { :id => 6,  :name => '6th' },
                { :id => 23, :name => 'New Mex' },
                { :id => 31, :name => 'Ute' } ],
      'FL' => [ { :id => 29, :name => 'Tallahasee' } ],
      'IA' => [ { :id => 5,  :name => '5th' } ],
      'ID' => [ { :id => 8,  :name => 'Boise' } ],
      'IL' => [ { :id => 2,  :name => '2nd' },
                { :id => 3,  :name => '3rd' },
                { :id => 4,  :name => '4th Illinois' } ],
      'IN' => [ { :id => 1,  :name => '1st' },
                { :id => 2,  :name => '2nd' } ],
      'KS' => [ { :id => 6,  :name => '6th' } ],
      'LA' => [ { :id => 18, :name => 'Louisiana' },
                { :id => 24, :name => 'St. Helena' } ],
      'MI' => [ { :id => 19, :name => 'Michigan' } ],
      'MN' => [ { :id => 5,  :name => '5th' },
                { :id => 46, :name => '4th' } ],
      'MO' => [ { :id => 5,  :name => '5th' } ],
      'MS' => [ { :id => 9,  :name => 'Chickasaw' },
                { :id => 10, :name => 'Choctaw' },
                { :id => 16, :name => 'Huntsville' },
                { :id => 25, :name => 'St. Stephens' },
                { :id => 32, :name => 'Washington' } ],
      'MT' => [ { :id => 20, :name => 'Prin' } ],
      'ND' => [ { :id => 5,  :name => '5th' } ],
      'NE' => [ { :id => 6,  :name => '6th' } ],
      'NM' => [ { :id => 23, :name => 'New Mex' } ],
      'NV' => [ { :id => 21, :name => 'Mount Diablo' },
                { :id => 27, :name => 'San Bernardino' } ],
      'OH' => [ { :id => 1,  :name => '1st' },
                { :id => 19, :name => 'Michigan' },
                { :id => 35, :name => 'Ohio River Survey' },
                { :id => 36, :name => 'Between the Miamis' },
                { :id => 37, :name => 'Muskingum River Basin' },
                { :id => 38, :name => 'Ohio River Basin' },
                { :id => 39, :name => '1st Scioto River Base' },
                { :id => 40, :name => '2nd Scioto River Base' },
                { :id => 41, :name => '3rd Scioto River Base' },
                { :id => 43, :name => 'Twelve Mile Square' },
                { :id => 47, :name => 'West of Great Miami' },
                { :id => 48, :name => 'US Military Survey' },
                { :id => 91, :name => 'Ct West Res-Ohio' },
                { :id => 92, :name => 'Ohio Co Pur-Ohio' },
                { :id => 93, :name => 'Va Military Survey-ohio' } ],
      'OK' => [ { :id => 11, :name => 'Cimarron' },
                { :id => 17, :name => 'Indian' } ],
      'OR' => [ { :id => 33, :name => 'Willamette' } ],
      'SD' => [ { :id => 5,  :name => '5th' },
                { :id => 6,  :name => '6th' },
                { :id => 7,  :name => 'Black Hills' } ],
      'UT' => [ { :id => 26, :name => 'Salt Lake' },
                { :id => 30, :name => 'Uintah Spec' } ],
      'WA' => [ { :id => 33, :name => 'Willamette' } ],
      'WI' => [ { :id => 46, :name => '4th' } ],
      'WY' => [ { :id => 6,  :name => '6th' },
                { :id => 34, :name => 'Wind River' } ] }
  end
end
